name: Pull request testing

on:
  pull_request

jobs:
  release:
    name: 'Run linter and tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Install dependencies
        run: npm ci
      - name: Should be able to build the library
        run: npm run build